### ISSUE TITLE
大佬能讲讲原理嘛

### ISSUE THREAD

**Issue by kaidegit** [Sirius0v0/DaoQiJieMi#1]

**Comment by Sirius0v0** [comment]
可以假定一种情况：三个机关三种状态；击打第一个机关连同第二个一起改变一次状态，击打第二个机关所有机关改变一次状态，击打第三个机关连同第二个一起改变一次状态；目标将所有机关状态改变至相同。
假设对第`i`个机关操作`xi`次（`i=1,2,3`），使得第`j`个机关状态改变了`yj`次（`j=1,2,3`），可以得出
> y1 = x1 + x2
y2 = x1 + x2 + x3
y3 = x2 + x3

写成矩阵形式记为：`y = Ax`
如果记机关组初状态向量为`α0`，期望状态向量为`α1`
则`y`应满足 `mod3( α0 + y )= α1` 【取模是考虑到机关只有三个状态】
根据上述可以整理得到 `y = Ax = α1 - α0`
方程可解需要`A`可逆则得到操作方法`x = A逆 (α1 - α0)`【结果注意取模就行了】
